frequency: 30.0
sensor_timeout: 0.1
two_d_mode: true

# Frames
map_frame: map
odom_frame: odom
base_link_frame: base_footprint
world_frame: map

# GPS input with better filtering
odom0: /odometry/gps_corrected
odom0_config:
  [true,  true,  false,   # Use x/y position from GPS
   false, false, false,   # No orientation from GPS
   false, false, false,   # No velocity from GPS
   false, false, false,   # No angular velocity from GPS
   false, false, false]   # No acceleration
odom0_differential: false
odom0_relative: false
odom0_queue_size: 10
odom0_pose_rejection_threshold: 10.0  # Reject GPS outliers

# IMU data
imu0: /imu
imu0_config:
  [false, false, false,   # No position
   true,  true,  true,    # Use roll, pitch, yaw
   false, false, false,   # No velocity
   false, false, false,   # No angular velocity in global frame
   false, false, false]   # No acceleration
imu0_differential: false
imu0_relative: false
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true
imu0_pose_rejection_threshold: 2.0  # Reject extreme orientation changes

# Add local odometry as an additional input for better stability
odom1: /odometry/local_filtered
odom1_config:
  [false, false, false,   # No position (we use GPS for that)
   false, false, false,   # No orientation (we use IMU for that)
   true,  true,  false,   # Use velocity from local odometry
   false, false, true,    # Use yaw velocity
   false, false, false]   # No acceleration
odom1_differential: false
odom1_relative: true
odom1_queue_size: 10

# Lower process noise for global position
process_noise_covariance: [0.005, 0,     0,     0,     0,     0,     0,      0,      0,     0,     0,     0,     0,     0,     0,
                           0,     0.005, 0,     0,     0,     0,     0,      0,      0,     0,     0,     0,     0,     0,     0,
                           0,     0,     0.06,  0,     0,     0,     0,      0,      0,     0,     0,     0,     0,     0,     0,
                           0,     0,     0,     0.03,  0,     0,     0,      0,      0,     0,     0,     0,     0,     0,     0,
                           0,     0,     0,     0,     0.03,  0,     0,      0,      0,     0,     0,     0,     0,     0,     0,
                           0,     0,     0,     0,     0,     0.06,  0,      0,      0,     0,     0,     0,     0,     0,     0,
                           0,     0,     0,     0,     0,     0,     0.025,  0,      0,     0,     0,     0,     0,     0,     0,
                           0,     0,     0,     0,     0,     0,     0,      0.025,  0,     0,     0,     0,     0,     0,     0,
                           0,     0,     0,     0,     0,     0,     0,      0,      0.04,  0,     0,     0,     0,     0,     0,
                           0,     0,     0,     0,     0,     0,     0,      0,      0,     0.01,  0,     0,     0,     0,     0,
                           0,     0,     0,     0,     0,     0,     0,      0,      0,     0,     0.01,  0,     0,     0,     0,
                           0,     0,     0,     0,     0,     0,     0,      0,      0,     0,     0,     0.02,  0,     0,     0,
                           0,     0,     0,     0,     0,     0,     0,      0,      0,     0,     0,     0,     0.01,  0,     0,
                           0,     0,     0,     0,     0,     0,     0,      0,      0,     0,     0,     0,     0,     0.01,  0,
                           0,     0,     0,     0,     0,     0,     0,      0,      0,     0,     0,     0,     0,     0,     0.015]

# Time and buffer settings
history_length: 5.0
transform_time_offset: 0.0
reset_on_time_jump: true
smooth_lagged_data: true
print_diagnostics: true

# Enhanced stability
predict_to_current_time: true
publish_acceleration: true

use_sim_time: true
publish_tf: true