# FILE: ekf_local.yaml
# PURPOSE: Fuses IMU data to produce a continuous but drifting odometry estimate in the 'odom' frame.

frequency: 30
sensor_timeout: 0.1
two_d_mode: true

# Frame and TF parameters
odom_frame: odom
base_link_frame: base_link
world_frame: odom  # IMPORTANT: This EKF operates in the odom frame

# Fuse IMU data. We fuse orientation and angular velocity.
imu0: /wamv/sensors/imu/imu/data
imu0_config:
  [false, false, false, # Do not fuse roll, pitch, yaw
   true,  true,  true,  # Fuse roll, pitch, yaw velocities
   false, false, false, # Do not fuse linear acceleration
   false, false, false, # (not used)
   false, false, false] # (not used)
imu0_differential: false # The IMU gives absolute orientation, but we are not fusing it here
imu0_relative: false
imu0_remove_gravitational_acceleration: true
imu0_ignore_bad_covariances: true