# FILE: ekf_global.yaml
# PURPOSE: Fuses the local odometry and GPS-derived odometry to produce a globally-correct state estimate in the 'map' frame.

frequency: 30
sensor_timeout: 0.1
two_d_mode: true

# Frame and TF parameters
odom_frame: odom
base_link_frame: base_link
world_frame: map  # IMPORTANT: This EKF operates in the global 'map' frame

# --- Sensor Inputs ---

# Input 1: The output of the local EKF
odom0: /odometry/filtered
odom0_config:
  [false, false, false,
   false, false, true,   # Do not fuse X, Y, Z position or roll, pitch. Fuse yaw.
   true,  true,  false,  # Fuse X, Y velocity. Do not fuse Z velocity.
   false, false, true,   # Do not fuse roll, pitch rates. Fuse yaw rate.
   false, false, false]
odom0_differential: false
odom0_relative: false

# Input 2: The output of navsat_transform_node. This provides the absolute position correction.
odom1: /odometry/gps
odom1_config:
  [true,  true,  false,  # Fuse X and Y position from GPS.
   false, false, false,
   false, false, false,
   false, false, false,
   false, false, false]
odom1_differential: false
odom1_relative: false

# Input 3: The raw IMU data. We fuse absolute heading (yaw) here.
imu0: /wamv/sensors/imu/imu/data
imu0_config:
  [false, false, false,
   false, false, true,   # Fuse absolute yaw from the IMU
   false, false, false,
   false, false, false,
   false, false, false]
imu0_differential: false
imu0_relative: false
imu0_remove_gravitational_acceleration: true
imu0_ignore_bad_covariances: true