# ====================================
# LOCAL COSTMAP
# ====================================
local_costmap:
  # Follow odometry frame for local updates
  global_frame: odom
  robot_base_frame: base_link

  update_frequency: 3.0        # Hz: how often to update from sensors
  publish_frequency: 3.0       # Hz: how often to publish for RViz
  static_map: false            # false → rolling window only
  rolling_window: true
  width: 3.0                   # meters: width of local window
  height: 3.0                  # meters: height of local window
  resolution: 0.05             # meters per cell
  transform_tolerance: 1.0     # sec: TF wait timeout

  # Obstacle layer settings
  obstacle_layer:
    observation_sources: laser_scan_sensor

    laser_scan_sensor:
      sensor_frame: base_scan
      data_type: LaserScan
      topic: /scan
      marking: true
      clearing: true

  # Layers to include in the local costmap
  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  # Inflation layer settings
  inflation_layer:
    inflation_radius:     0.20   # meters: tighter local buffer
    cost_scaling_factor:  5.0    # gentler cost gradient for reactivity


# ====================================
# GLOBAL PLANNER & CONTROLLER
# ====================================
planner_frequency:    2.0    # Hz: how often to run global planning
planner_patience:     5.0    # sec: max wait for a valid global plan

controller_frequency: 1.0    # Hz: how often to run local planner
controller_patience:  15.0   # sec: max wait for a valid control command

# Local planner choice
base_local_planner: "dwa_local_planner/DWAPlannerROS"

DWAPlannerROS:
  # Velocity limits (m/s and rad/s)
  max_vel_x:               0.22
  min_vel_x:              -0.22
  max_vel_y:               0.00
  min_vel_y:               0.00
  max_vel_trans:           0.22
  min_vel_trans:           0.11
  max_vel_theta:           2.75
  min_vel_theta:           1.37

  # Acceleration limits
  acc_lim_x:               2.50
  acc_lim_y:               0.00
  acc_lim_theta:           3.20

  # Goal tolerances
  xy_goal_tolerance:       0.25   # meters
  yaw_goal_tolerance:      0.30   # radians
  latch_xy_goal_tolerance: false

  # Simulation parameters for trajectory sampling
  sim_time:                2.0
  sim_granularity:         0.025
  angular_sim_granularity: 0.025
  vx_samples:             20
  vy_samples:              0
  vth_samples:            40

  # Controller update and TF tolerances
  controller_frequency:   1.0
  transform_tolerance:     1.0


# ====================================
# RECOVERY BEHAVIORS
# ====================================
recovery_behavior_enabled:   true   # allow recovery on failure
clearing_rotation_allowed:   true   # enable in-place rotation to clear obstacles
conservative_reset_dist:     0.30   # meters: how far back to clear costmap

use_sim_time: true
