# General move_base parameters (optional, can be added here)
# controller_frequency: 10.0
# planner_patience: 5.0

# ============ Global Costmap (in ODOM frame) ============
global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 300.0
  height: 300.0
  resolution: 0.5

  plugins:
    - {name: obstacle_layer,   type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}

  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
      sensor_frame: lidar_link
      data_type: LaserScan
      topic: /scan_scaled
      marking: true
      clearing: true
      max_obstacle_height: 2.0
      min_obstacle_height: 0.0
      obstacle_range: 9.0
      raytrace_range: 10.0

  inflation_layer:
    inflation_radius: 1.2
    cost_scaling_factor: 5.0

# ============ Local Costmap (in ODOM frame) ============
local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 15.0
  height: 15.0
  resolution: 0.1

  plugins:
    - {name: obstacle_layer,   type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}

  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
      sensor_frame: lidar_link
      data_type: LaserScan
      topic: /scan_scaled
      marking: true
      clearing: true
      max_obstacle_height: 2.0
      min_obstacle_height: 0.0
      obstacle_range: 9.0
      raytrace_range: 10.0

  inflation_layer:
    inflation_radius: 1.0
    cost_scaling_factor: 10.0

# ============ DWA Planner ============
DWAPlannerROS:
  xy_goal_tolerance:      2.0
  yaw_goal_tolerance:     3.14
  latch_xy_goal_tolerance: true

  trans_stopped_vel:      10.0
  rot_stopped_vel:        10.0
  stop_time_buffer:       0.0

  acc_lim_x:          0.1
  acc_lim_theta:      0.5
  max_vel_x:          0.3
  max_vel_theta:      0.5
  path_distance_bias: 20.0
  goal_distance_bias: 30.0
  occdist_scale:      0.1
  oscillation_timeout:    3.0
  oscillation_distance:   0.20