# FILE: navsat_transform.yaml
# PURPOSE: Uses GPS and IMU heading to create the map->odom transform.

frequency: 30
delay: 3.0
magnetic_declination_radians: 0.0  # Find your location's declination and convert to radians!
yaw_offset: 1.5707963                # Offset for IMU facing North (Ï€/2). Adjust if your IMU has a different orientation.
zero_altitude: true

# Set this to true! We want to use the velocity from the local EKF for a smoother output.
use_odometry: true
publish_filtered_gps: true
broadcast_utm_transform: true