frequency: 30.0
delay: 3.0
magnetic_declination_radians: 0.0
yaw_offset: 0.0

# Critical settings
use_odometry_yaw: true
use_magnetic_field_as_heading: false
wait_for_datum: false
broadcast_cartesian_transform: true
publish_filtered_gps: true
zero_altitude: true

# Enhanced GPS filtering
permit_corrected_publication: true
transform_timeout: 0.5
# Add this to help filter noisy GPS readings
gps_covariance_type: 2  # Automatic covariance based on DOP values
noise_minimum: 0.001

# Frame definitions
world_frame: odom
base_link_frame: base_footprint
use_sim_time: true